import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ResothoExtra = localFont({
  src: [
    {
      path: "../../public/assets/fonts/resothoextralight/resothoextralight.otf",
    },
  ],
  variable: "--font-resothoextralight",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={ResothoExtra.className}
      >
        {children}
      </body>
    </html>
  );
}
