import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lato } from "next/font/google";
import "./globals.css";

const Resotho = localFont({
  src: [
    {
      path: "../../public/assets/fonts/resothoextralight/resothoextralight.otf",
    },
  ],
  variable: "--font-resotho",
});

const LatoFont = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], 
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Exchange App",
  description: "Generated by exchange",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
           <body className={`${Resotho.variable} ${LatoFont.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
